### PR TITLE
Remove offline install override

### PR DESCRIPTION
**Pull request by bndabbs**
Related to https://github.com/rocknsm/rock/pull/378

### CODE REVIEW

**Comment by spartan782** [comment]
Don't we want to keep this to default to offline from ISO install? We would want to change the default behavior of the RPM to set it to an online install and to ignore the offline folder.

**Comment by bndabbs** [comment]
Good point @spartan782. I fixed that with 5efe306.

**Comment by spartan782** [comment]
Does that mean we can close this pull request? or am I missing something?

**Comment by bndabbs** [comment]
It just needs to be merged in. We should wait until rocknsm/rock#378 is merged though, because the nightly build will start failing until that is in devel

**Pull request merged**
